[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "2eeb18914f384daa3cb1481055edd43fc464ae74"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "3cb0bf9b748095624f76c665c62d604b692f4cb334420c83226d85d665a8f65f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "8af142593c6632e5fd803da8b7914e738ae38e6d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "8b55ce92d9afa8aec1f0c5a7e4851cf5e7fa43a8cab351ea52e118c8aea108ec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "2b14846e26d1abce3b54ccd22b6113b33d8a704c"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "61da35ca5a618887562c9fb615b028d1e508e2d12234a3b15eb11c13dd8da401"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "bb853ebd297daad0b7528bd2e1fce8ad156682b8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "c9dbfcb8d78baec67716f1034466996fec24939b614c7558d218d425f48f2d59"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "ea2c70509dbe1522e18ddd537a6c024952ffa65c"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "cf0e261b5512c25c37fc3af72ac081f3886fc8f7d8f1657528daccd275404f4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "95a61bf187ec5ade136c67714af5f6fb2291adb8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "c78270dd545fb1b5ba0ae89e04e5f652afdada0a68d25f542bb54d88efc776b9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "96c47559b100c6d695d4d69f40f4eac07208d6bd"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "4ca4ddee69f29595f32d3b64117f2e2b8ca916d79b5a317cfcb739445c8d74bd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "7f5ba6d9eed49843f1c5d26343ad5fcc044ce671"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "26e1ae5961140ff2d8884132e001807297b7ca095274d0de8742c2e05ab5d560"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.501+0/GAP_pkg_nq.v200.500.501.x86_64-unknown-freebsd.tar.gz"
