[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "e1fd755c0aee84d021e33796d84c56db9733c4a3"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "4274c114022c775400b4ff7626ff8c39beea782fc5cb17f08ea0ad7d8a1b026b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "a51015a2261267e59472f8f75ce651a7f6df7d50"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "b1feb0ad950e509c2744147575eae74b09585edd0484b83201ec2e921da3d567"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "2eed758081274345d891ce3e193fc60c8b6a81b6"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "d757e40d96e1d81d6b3dc50b9ece33610819d2a8df0be43b58538721149bb9a2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "2bebae32d83bfc8c0a427779aede4110d383d93c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "206bbbf752d1f7272f66572ab7317c5c954c870189d004486ff7f15ac836d15e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "c0e2d47f442cc492a00adc723ff615a55ca4fc6d"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "312f79c250a4b70e0c46d64482d75f1bc77c648468e7a78905e8e931f918e3a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "f1c3d0fb2ac1e15876c0aeae02aa71a1ea37e27f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "be648051d74cc1f7cbe592d25be0221c7a52732fd57fb3c665f94d2683020cb4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "cd1f19ea0b7913ae84ca997070f5e82fc4ba49f7"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "dfc72b411f9aafb9aed02d50de29a6b84d875695dc378d7fd55946d434def0be"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "69caa1698c4baab0eee13d4c88072c102121bb7c"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "ef5fe8e01c3a3184455f540c28e7b22e10559c610f1de2815224bdee22468dc8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+0/GAP_pkg_nq.v200.500.800.x86_64-unknown-freebsd.tar.gz"
