[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "4d47a8c3c5731dc26ffc8c69e5c43277f36561ae"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "891242c4193ebe63a37d41975a2519ac22c83f1875fc8da13d6c66865ac78fc3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "9c90f38b63064d67da7a5ee8a4725dfe873d5cfe"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "cc9c7d67cafad817d9823984d724520eb97853c341173504b5c2f4c752b3d76e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "df81c2c819db7016e6b6752e492c6dd59b9976e1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "276a4648bc4e00bbd587aff807db89365fd0600f0fffae7bcf69b18556d5d923"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "9cbf34736888ff2bf137316f6e8de58652952b21"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "4a5268446bf71217a2b8637858c4e08b69fbdec7411c2a1d533b7cc84eaf5f74"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "8492e846d5d9a489d3aa97769b9bf3691826f9d2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "0fa38c290d7e0d83c3e96c05d7fb2c2dbc1b662ec7469141571d32ef35741e95"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "3ef1d2aeff312467679eb1079dccfa70a75d8b1d"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "b22cb30fbde66ba6e98d37ff2a0e1acb920da151156a845101d6db9fdbbda573"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "2474a3e8741b4c44d0d78285d3b6762a1e50e133"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "b9a9bc8f954447caf6bfb537ffe3e2d47e8159a6490d3b7a53ce3f9280bb1503"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.500+0/GAP_pkg_nq.v200.500.500.x86_64-unknown-freebsd.tar.gz"
