[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "e1fd755c0aee84d021e33796d84c56db9733c4a3"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "abacf9c3fa01395d04cf099c5ee89d1164ba7773a407f78f2d5e0c8ea2aa8dfc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "a51015a2261267e59472f8f75ce651a7f6df7d50"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "4481df6ea7b474ae1c63228f384d9d44bf09200a13c619de2a84e137584475e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "2eed758081274345d891ce3e193fc60c8b6a81b6"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "59c84634f29519b5688959b2c09e308e08e1db2a44da50992c523a8146c738a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "2bebae32d83bfc8c0a427779aede4110d383d93c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "0eef2b1ca4e021caeec9d948346bec61f1407985b45270eedfb21255e67d9820"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "c0e2d47f442cc492a00adc723ff615a55ca4fc6d"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "15b6072756db9a1b1cbfc9db73a70cac7ad2f14a58dcadab6fbd846bb181b68d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "f1c3d0fb2ac1e15876c0aeae02aa71a1ea37e27f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "97c5de5720807e8030edcdda49ba26fd2b68e27e7e813fcc329215e17f5474eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "cd1f19ea0b7913ae84ca997070f5e82fc4ba49f7"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "73251466beba8c31198e2425cc3dc11cff10bb4c612cbe545bca37c8bb588b44"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "69caa1698c4baab0eee13d4c88072c102121bb7c"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "c5a5422c19ecef58ed98fd140440f0fd382b6317a7c58eb0f92489e9b0fd9011"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.800+1/GAP_pkg_nq.v200.500.800.x86_64-unknown-freebsd.tar.gz"
