[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "32d24c998668751298e54d1becd863e38b4388a4"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "2cca51d916abacb874c61f6bf191394203961b40f1b85fb9f199e778dab12827"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "ad0880bdbe6c351373adbed35e498833184cdee0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "a375f3bdcbf50dbd48ab6fc14b5cb1000a9c2d64570a7cceaa724f9565b8475e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "2de9f314155f8fe67ef63a7f5542412d929ad655"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "f7080998c73fa0ed9f888df84995f5317e4a8bca7a24d6dd628ec8713cc1f212"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "61163be4d549b77d60025b136875b10935bb3057"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "cbd98b58040401270bb7421dcc82faf17e9cd5a50bc8ea1fbf42425477b1af14"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "7b7198498cc4f765ad201cc8d6cb19cc8ec962f8"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "40a4788127dfba96a9f7e46ce149e8d17de1bc0f21c0d706deb7e7ce622943c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "b10df779e97b66f2defddaf9c53b9728b652a3a6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "8d67c7c46646f6d456e998dd4d53fa5fb54847c7977f2a720bfe9cca9ce6e000"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "83d5f18e1a4c8b5f39e68d2c81736a7e5b17fd38"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "d4132cf77a51f5f9ea4d9d4acc30174c537e83705f3d28726faf41d22d9e1eba"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "478592d4d869c94c2cdd1da5869970610be0dc91"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "0e2578bbdb3ffcbacb266bb65c499f422a80673e75f507748713b4aa50919d84"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.1100+0/GAP_pkg_nq.v200.500.1100.x86_64-unknown-freebsd.tar.gz"
