[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "002a3ffac716c47caafddec0edc02952b3c612db"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "ae1cfb2b46df2735229b53a22c9530976051d15eda1ab3bf1395f2b72c86b6b7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "af949275af8c9da57723ce3aaad63e662efcdf3f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "279d704773a2db58710202d7bacc62cfc8910f5128ef3d4be6009e3ef1fcef4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "aarch64"
git-tree-sha1 = "b5c9a76d6c1d5bda61e12ccff139fff17ca6d9ff"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "2e5cb65b5e33f4130048fd683ea5b627596820c37647161f947ade6f0525da46"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.aarch64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "powerpc64le"
git-tree-sha1 = "1afbaee73bbd97544c1aefb453dce11273867a2e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "3d70431bdc513cc8205bd1155effeaa03d46070990d1ae3f179124902b32ef43"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "0eaba6eec88de3cd181a68e3e037ab1a8f917630"
os = "macos"

    [[GAP_pkg_nq.download]]
    sha256 = "6a5c4b1d4fa0a9f6fb5549ae0cdd928a0f5bebbfb1351440b3c6634e08d01045"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "42a0f817841a95da60d4aefe3557fc5b6a1613dc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "9a12389a65472043b0a4a3a8003f910db57a1f9e0fe9844fb23ea9537e666446"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "6ee2de082ae3147741da299e748142cd04aa6617"
libc = "musl"
os = "linux"

    [[GAP_pkg_nq.download]]
    sha256 = "c6a1dadcd33fe94a816e01bba8cedf90c5bca6a2c4ec6b949b6bc4458494e712"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.x86_64-linux-musl.tar.gz"
[[GAP_pkg_nq]]
arch = "x86_64"
git-tree-sha1 = "c1717faeaf15d360c183d3ac251b7688121c57c8"
os = "freebsd"

    [[GAP_pkg_nq.download]]
    sha256 = "687c5f359b1cb3acdc785fd9518ef405b8b9068f114a343ab2439a6c1da3c3bb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_nq_jll.jl/releases/download/GAP_pkg_nq-v200.500.900+0/GAP_pkg_nq.v200.500.900.x86_64-unknown-freebsd.tar.gz"
